const $=id=>document.getElementById(id);const rupiah=n=>'Rp '+Number(n||0).toLocaleString('id-ID');const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={config:{},dashboard:{},transaksi:[],warga:[],statusIuran:[],program:[],selectedType:'PEMASUKAN',admin:false,token:sessionStorage.getItem('rt001_token')||''};
const CATS={PEMASUKAN:['IURAN BULANAN','JIMPITAN','DONASI','BANTUAN','LAINNYA'],PENGELUARAN:['OPERASIONAL RT','KEGIATAN RT','KEBERSIHAN','KEAMANAN','SOSIAL','PEMBELIAN','LAINNYA']};
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),3500)}
function errorToast(e){console.error(e);toast('⚠ '+(e?.message||e))}
function setServer(ok,text){const e=$('serverPill');e.className='server-pill '+(ok?'online':'offline');e.innerHTML=`<i></i>${esc(text)}`}
function showModal(id){$(id).classList.add('show')};function closeModal(id){$(id).classList.remove('show')}
function navigate(page){document.querySelectorAll('.page').forEach(e=>e.classList.remove('active'));document.querySelectorAll('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===page));$('page-'+page)?.classList.add('active');$('sidebar').classList.remove('open');if(page==='transactions')renderTransactions();if(page==='warga')renderWarga();if(page==='iuran')renderIuran();if(page==='program')renderPrograms();if(page==='reports')renderReport()}
function fmtDate(s){if(!s)return'-';return String(s).slice(0,10)}
function shortId(s){s=String(s||'');return s.length>16?s.slice(0,8)+'…'+s.slice(-4):s}
function typeBadge(t){const inx=String(t).toUpperCase()==='PEMASUKAN';return `<span class="badge ${inx?'in':'out'}">${inx?'↑':'↓'} ${inx?'Masuk':'Keluar'}</span>`}
function activeTransactions(){return state.transaksi.filter(t=>String(t.status).toUpperCase()!=='DIHAPUS')}
function transactionTable(rows,admin=true){if(!rows.length)return '<div class="empty">Belum ada transaksi.</div>';return `<table><thead><tr><th>ID</th><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th><th>Status</th>${admin?'<th>Aksi</th>':''}</tr></thead><tbody>${rows.map(t=>{const inx=t.tipe==='PEMASUKAN',active=t.status==='AKTIF';return `<tr><td><code>${esc(shortId(t.id))}</code></td><td>${esc(fmtDate(t.tanggal))}</td><td>${typeBadge(t.tipe)}</td><td>${esc(t.kategori)}</td><td>${esc(t.keterangan)}</td><td class="${inx?'money-in':'money-out'}">${inx?'+':'−'} ${rupiah(t.nominal)}</td><td>${active?'<span class="badge ok">AKTIF</span>':'<span class="badge off">DIBATALKAN</span>'}</td>${admin?`<td>${active?`<button class="secondary mini" data-edit="${esc(t.id)}">Edit</button> <button class="secondary mini" data-delete="${esc(t.id)}">Batal</button>`:'—'}</td>`:''}</tr>`}).join('')}</tbody></table>`}
function renderDashboard(){const d=state.dashboard||{};$('saldo').textContent=rupiah(d.saldo);$('pemasukan').textContent=rupiah(d.bulanIni?.pemasukan??d.pemasukan);$('pengeluaran').textContent=rupiah(d.bulanIni?.pengeluaran??d.pengeluaran);$('jumlahTransaksi').textContent=activeTransactions().length;$('saldoMeta').textContent='Server verified · '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});const r=activeTransactions().slice(0,8);$('recentTable').innerHTML=transactionTable(r,false);const i=state.dashboard?.iuran||{};$('iuranPct').textContent=(i.persentaseLunas||0)+'%';$('iuranLunas').textContent=i.lunas||0;$('iuranBelum').textContent=i.belumBayar||0;$('iuranWarga').textContent=i.totalWarga||0;$('donut').style.background=`conic-gradient(#2b8b5d ${(i.persentaseLunas||0)*3.6}deg,#e8efeb 0deg)`}
function renderCategories(){const list=CATS[state.selectedType]||[];$('kategori').innerHTML='<option value="">Pilih kategori</option>'+list.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderWargaSelect(){const active=state.warga.filter(w=>String(w.statusAktif).toUpperCase()==='AKTIF');$('idWarga').innerHTML='<option value="">Tidak terkait warga tertentu</option>'+active.map(w=>`<option value="${esc(w.id)}">${esc(w.nama)}</option>`).join('')}
function renderTransactions(){let rows=activeTransactions(),q=$('search').value.trim().toLowerCase(),kind=$('filterJenis').value;rows=rows.filter(t=>(!q||[t.id,t.kategori,t.keterangan].join(' ').toLowerCase().includes(q))&&(!kind||t.tipe===kind));$('transactionTable').innerHTML=transactionTable(rows,state.admin)}
function renderWarga(){const q=$('wargaSearch').value.trim().toLowerCase();const rows=state.warga.filter(w=>!q||[w.nama,w.alamat,w.hp].join(' ').toLowerCase().includes(q));$('wargaCount').textContent=`${state.warga.filter(w=>w.statusAktif==='AKTIF').length} warga aktif · ${state.warga.length} total`;$('wargaTable').innerHTML=rows.length?`<table><thead><tr><th>Nama KK</th><th>Gender</th><th>WhatsApp</th><th>Alamat</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(w=>`<tr><td><b>${esc(w.nama)}</b></td><td>${esc(w.gender)}</td><td>${esc(w.hp||'-')}</td><td>${esc(w.alamat||'-')}</td><td>${w.statusAktif==='AKTIF'?'<span class="badge ok">AKTIF</span>':'<span class="badge off">NONAKTIF</span>'}</td><td>${state.admin?`<button class="secondary mini" data-wedit="${esc(w.id)}">Edit</button>`:'—'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Data warga belum ada.</div>'}
function renderIuran(){const rows=state.statusIuran||[];const i=state.dashboard?.iuran||{};$('iTotal').textContent=i.totalWarga||0;$('iPaid').textContent=i.lunas||0;$('iUnpaid').textContent=i.belumBayar||0;$('iPercent').textContent=(i.persentaseLunas||0)+'%';const q=$('iuranSearch').value.trim().toLowerCase();const filtered=rows.filter(w=>!q||w.nama.toLowerCase().includes(q));$('iuranTable').innerHTML=filtered.length?`<table><thead><tr><th>Nama KK</th><th>WhatsApp</th><th>Status Iuran</th></tr></thead><tbody>${filtered.map(w=>`<tr><td><b>${esc(w.nama)}</b></td><td>${esc(w.hp||'-')}</td><td>${w.statusIuran==='LUNAS'?'<span class="badge ok">✓ LUNAS</span>':'<span class="badge warn">BELUM BAYAR</span>'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Belum ada data iuran.</div>'}
function renderPrograms(){const rows=state.program||[];$('programGrid').innerHTML=rows.length?rows.map(p=>{const progress=Math.min(100,Math.max(0,Number(p.progres)||0));return `<article class="program-card"><span class="section-tag">${esc(p.status||'PROGRAM')}</span><h3>${esc(p.nama)}</h3><p>${esc(p.deskripsi||'Tidak ada deskripsi.')}</p><div class="progress"><i style="width:${progress}%"></i></div><div class="program-meta"><span>${progress}% selesai</span><span>${rupiah(p.targetAnggaran)}</span></div>${state.admin?`<button class="secondary full" style="margin-top:14px" data-progress="${esc(p.id)}">Update progres</button>`:''}</article>`}).join(''):'<div class="empty">Belum ada program RT.</div>'}
function renderReport(){const d=state.dashboard||{};$('reportPreview').innerHTML=`<span class="section-tag">RINGKASAN TERKINI</span><h2>Kas ${esc(state.config.rt||'RT 001')} / ${esc(state.config.rw||'RW 001')}</h2><p class="muted">${esc(state.config.dukuh||'Dukuh Gajah')} · ${esc(state.config.desa||'Surorejan')} · ${esc(state.config.kecamatan||'Puring')} · ${esc(state.config.kabupaten||'Kebumen')}</p><div class="iuran-summary"><div class="metric"><span>Saldo</span><strong>${rupiah(d.saldo)}</strong></div><div class="metric"><span>Pemasukan bulan ini</span><strong>${rupiah(d.bulanIni?.pemasukan)}</strong></div><div class="metric"><span>Pengeluaran bulan ini</span><strong>${rupiah(d.bulanIni?.pengeluaran)}</strong></div><div class="metric"><span>Transaksi aktif</span><strong>${activeTransactions().length}</strong></div></div>`}
function setAdmin(on,token=''){state.admin=on;state.token=token||state.token;if(on)sessionStorage.setItem('rt001_token',state.token);else{state.token='';sessionStorage.removeItem('rt001_token')}$('adminBtn').textContent=on?'Admin aktif':'Admin';$('adminStatus').textContent=on?'✓ Mode administrator aktif':'Belum login sebagai administrator';renderTransactions();renderWarga();renderPrograms()}
async function load(){setServer(false,'Menghubungkan');try{const d=await KasApi.getInitialData();state.config=d.config||{};state.dashboard=d.dashboard||{};state.transaksi=(d.transaksi||[]).map(KasApi.normalizeTransaction);state.warga=d.warga||[];state.statusIuran=d.statusIuran||[];state.program=d.program||[];setServer(true,'Database online');$('brandTitle').textContent=`${state.config.rt||'RT 001'} / ${state.config.rw||'RW 001'}`;$('brandSub').textContent=`${state.config.dukuh||'Dukuh Gajah'} · ${state.config.desa||'Surorejan'}`;$('dueDate').textContent=state.config.jatuhTempo||5;$('feeAmount').textContent=rupiah(state.config.iuranBulanan||10000);renderCategories();renderWargaSelect();renderDashboard();renderTransactions();renderWarga();renderIuran();renderPrograms();renderReport()}catch(e){setServer(false,'Database offline');errorToast(e)}}
function setToday(){const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);$('tanggal').value=x}
async function requireAdmin(){if(state.admin&&state.token)return true;showModal('loginModal');return false}
$('adminBtn').onclick=()=>showModal('adminModal');$('loginForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const r=await KasApi.login($('loginPassword').value);if(!r.sessionToken)throw Error('Server tidak mengembalikan session token.');setAdmin(true,r.sessionToken);closeModal('loginModal');$('loginPassword').value='';toast('✓ Login administrator berhasil')}catch(err){errorToast(err)}finally{b.disabled=false}};
$('logoutBtn').onclick=async()=>{try{if(state.token)await KasApi.logout(state.token)}catch(e){}setAdmin(false);closeModal('adminModal');toast('Anda telah keluar dari mode admin.')};
document.querySelectorAll('.nav,[data-page]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.page)navigate(b.dataset.page)}));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
document.querySelectorAll('.type-btn').forEach(b=>b.onclick=()=>{state.selectedType=b.dataset.type;document.querySelectorAll('.type-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCategories()});
$('transactionForm').onsubmit=async e=>{e.preventDefault();if(!(await requireAdmin()))return;const b=e.submitter;const payload={sessionToken:state.token,tanggal:$('tanggal').value,tipe:state.selectedType,kategori:$('kategori').value,nominal:Number($('nominal').value),keterangan:$('keterangan').value.trim(),idWarga:$('idWarga').value,admin:'Administrator'};if(!payload.kategori||!payload.keterangan||payload.nominal<=0)return toast('Lengkapi kategori, keterangan, dan nominal.');b.disabled=true;b.textContent='Menyimpan…';try{await KasApi.createTransaction(payload);await load();e.target.reset();setToday();toast('✓ Transaksi berhasil disimpan')}catch(err){errorToast(err)}finally{b.disabled=false;b.textContent='Simpan transaksi'}};
$('refreshBtn').onclick=load;['search','filterJenis'].forEach(id=>$(id).oninput=renderTransactions);$('wargaSearch').oninput=renderWarga;$('iuranSearch').oninput=renderIuran;
document.addEventListener('click',e=>{if(e.target.dataset.edit){const t=state.transaksi.find(x=>x.id===e.target.dataset.edit);if(t){$('editId').value=t.id;$('editDate').value=String(t.tanggal||'').slice(0,10);$('editNominal').value=t.nominal;$('editKategori').value=t.kategori;$('editKeterangan').value=t.keterangan;$('editReason').value='';showModal('editModal')}}if(e.target.dataset.delete){$('actionId').value=e.target.dataset.delete;$('actionReason').value='';showModal('actionModal')}if(e.target.dataset.wedit){const w=state.warga.find(x=>x.id===e.target.dataset.wedit);if(w){$('wargaId').value=w.id;$('wargaNama').value=w.nama;$('wargaGender').value=w.gender;$('wargaHp').value=w.hp;$('wargaAlamat').value=w.alamat;$('wargaStatus').value=w.statusAktif;$('wargaKet').value=w.keterangan||'';$('wargaModalTitle').textContent='Edit warga';showModal('wargaModal')}}if(e.target.dataset.progress){const p=prompt('Masukkan progres 0–100:');if(p!==null&&state.token)KasApi.updateProgress({sessionToken:state.token,id:e.target.dataset.progress,progres:Number(p)}).then(()=>{load();toast('✓ Progres diperbarui')}).catch(errorToast)}});
$('editForm').onsubmit=async e=>{e.preventDefault();if(!(await requireAdmin()))return;try{await KasApi.updateTransaction({sessionToken:state.token,id:$('editId').value,tanggal:$('editDate').value,tipe:state.transaksi.find(t=>t.id===$('editId').value)?.tipe,kategori:$('editKategori').value,nominal:Number($('editNominal').value),keterangan:$('editKeterangan').value,alasanEdit:$('editReason').value,admin:'Administrator'});closeModal('editModal');await load();toast('✓ Transaksi diperbarui & masuk audit trail')}catch(e){errorToast(e)}};
$('actionForm').onsubmit=async e=>{e.preventDefault();if(!(await requireAdmin()))return;try{await KasApi.cancelTransaction({sessionToken:state.token,id:$('actionId').value,alasanEdit:$('actionReason').value,admin:'Administrator'});closeModal('actionModal');await load();toast('✓ Transaksi dibatalkan')}catch(e){errorToast(e)}};
$('addWargaBtn').onclick=()=>{if(!state.admin)return showModal('loginModal');$('wargaForm').reset();$('wargaId').value='';$('wargaModalTitle').textContent='Tambah warga';showModal('wargaModal')};$('wargaForm').onsubmit=async e=>{e.preventDefault();if(!state.admin)return showModal('loginModal');const base={sessionToken:state.token,id:$('wargaId').value,nama:$('wargaNama').value,gender:$('wargaGender').value,hp:$('wargaHp').value,alamat:$('wargaAlamat').value,statusAktif:$('wargaStatus').value,keterangan:$('wargaKet').value,admin:'Administrator'};try{if(base.id)await KasApi.updateWarga(base);else await KasApi.createWarga(base);closeModal('wargaModal');await load();toast('✓ Data warga tersimpan')}catch(e){errorToast(e)}};
$('addProgramBtn').onclick=()=>{if(!state.admin)return showModal('loginModal');$('programForm').reset();showModal('programModal')};$('programForm').onsubmit=async e=>{e.preventDefault();if(!state.admin)return showModal('loginModal');try{await KasApi.createProgram({sessionToken:state.token,nama:$('programNama').value,tanggalRapat:$('programTanggal').value,deskripsi:$('programDeskripsi').value,targetAnggaran:Number($('programAnggaran').value||0),progres:Number($('programProgres').value||0),penanggungJawab:$('programPJ').value,catatan:$('programCatatan').value});closeModal('programModal');await load();toast('✓ Program tersimpan')}catch(e){errorToast(e)}};
$('passwordForm').onsubmit=async e=>{e.preventDefault();if(!state.admin)return;try{await KasApi.changePassword({sessionToken:state.token,passwordBaru:$('newPassword').value});e.target.reset();toast('✓ Password administrator diperbarui')}catch(err){errorToast(err)}};
$('printBtn').onclick=()=>{const html=`<html><head><title>Laporan Kas RT</title><style>body{font:14px Arial;padding:35px;color:#17231e}h1{margin-bottom:4px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:8px;border:1px solid #ddd;text-align:left}th{background:#f1f5f3}</style></head><body><h1>Laporan Kas ${esc(state.config.rt)} / ${esc(state.config.rw)}</h1><p>${esc(state.config.dukuh)} · ${esc(state.config.desa)} · ${esc(state.config.kecamatan)} · ${esc(state.config.kabupaten)}</p><h2>Saldo: ${rupiah(state.dashboard.saldo)}</h2>${transactionTable(activeTransactions(),false)}</body></html>`;const w=window.open('','_blank');if(!w)return toast('Izinkan popup untuk mencetak laporan.');w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),300)};
$('whatsappBtn').onclick=()=>{const d=state.dashboard,i=d.iuran||{};const text=`*LAPORAN KAS ${state.config.rt||'RT 001'} / ${state.config.rw||'RW 001'}*\n${state.config.dukuh||'Dukuh Gajah'} · ${state.config.desa||'Surorejan'}\n\nSaldo saat ini: *${rupiah(d.saldo)}*\nPemasukan bulan ini: ${rupiah(d.bulanIni?.pemasukan)}\nPengeluaran bulan ini: ${rupiah(d.bulanIni?.pengeluaran)}\nTransaksi aktif: ${activeTransactions().length}\nIuran bulan ini: ${i.persentaseLunas||0}% warga lunas\n\n_Laporan dibuat dari Sistem Kas RT._`;window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')};
setToday();if(state.token)setAdmin(true,state.token);load();